"""Add profit_rate and end_date to Investment

Revision ID: 12153f573797
Revises: 417c37237424
Create Date: 2024-11-28 04:31:14.666251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12153f573797'
down_revision = '417c37237424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.alter_column('current_year',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.alter_column('current_year',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
