"""Add profit_rate and end_date to Investment

Revision ID: b51f3166d573
Revises: 12153f573797
Create Date: 2024-11-28 04:32:13.641529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51f3166d573'
down_revision = '12153f573797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profit_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('profit_rate')

    # ### end Alembic commands ###
